version: "2"

linters:
  disable-all: true
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - dupl
    - durationcheck
    - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - godot
    - goprintffuncname
    - grouper
    - importas
    - intrange
    - makezero
    - mirror
    - misspell
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - reassign
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gochecksumtype:
    default-signifies-exhaustive: false

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - goconst
        - forcetypeassert
