version: "2"

linters:
  default: none
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - dupl
    - durationcheck
    - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - godot
    - goprintffuncname
    - grouper
    - importas
    - intrange
    - makezero
    - mirror
    - misspell
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - reassign
    - testifylint
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
