version: '3'

tasks:
  gen:
    desc: "Generate protobuf Go types"
    preconditions:
      - sh: which protoc
        msg: "`protoc` not found. Install from https://grpc.io/docs/protoc-installation/"
      - sh: which protoc-gen-go
        msg: "`protoc-gen-go` not found. Install via: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
    sources:
      - s2-protos/**/*.proto
    generates:
      - generated/**/*.go
    cmds:
      - mkdir -p generated
      - cmd: |
          protoc --go_out=generated \
            --go_opt=paths=import \
            --go_opt=Ms2-protos/s2/v1/s2.proto=. \
            s2-protos/s2/v1/s2.proto

  test:
    deps: [gen]
    cmds:
      - go test ./...

  test:integration:
    desc: "Run integration tests"
    deps: [gen]
    cmds:
      - go test -v -timeout 10m -count=1 -run 'Test(List|Create|Get|Delete|Reconfigure)(Basin|Stream)|Test(CheckTail|Append|Read|Fence|Trim|Client|AppendSession|ReadSession)|Test(List|Issue|Revoke)AccessToken|Test(Account|Basin|Stream)?Metrics' ./s2

  lint:
    deps: [gen]
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then \
          golangci-lint run; \
        else \
          echo "golangci-lint not installed; skip lint" >&2; \
        fi

  eg:
    desc: "Run an example. Usage: task eg NAME=readsession"
    requires:
      vars: [NAME]
    cmds:
      - task: eg:build
        vars: { NAME: '{{.NAME}}' }
      - .out/examples/{{.NAME}} {{.CLI_ARGS}}

  eg:build:
    deps: [gen]
    requires:
      vars: [NAME]
    cmds:
      - mkdir -p .out/examples
      - go build -o .out/examples/{{.NAME}} ./examples/{{.NAME}}

  lint:gen:
    deps: [gen]
    cmds:
      - |
        # Ignore version comment lines (protoc-gen-go and protoc versions)
        git diff generated/*.go | grep -v '^[-+]//.*protoc' | grep -q '^[-+]' && {
            echo "Generated code has changed (ignoring version comments)"
            echo "Run 'task gen' and commit the generated code"
            exit 1
        } || echo "Up-to-date"

  release:prepare:
    requires:
      vars: [VERSION]
    vars:
      SEMVER:
        sh: ./scripts/semver.sh {{.VERSION}}
      BRANCH: 'release-{{.SEMVER}}-{{now | unixEpoch}}'
    cmds:
      - git fetch origin -t
      - git checkout origin/main
      - git switch -c {{.BRANCH}}
      - git cliff -o CHANGELOG.md --tag {{.SEMVER}}
      - git add CHANGELOG.md
      - 'git commit -m "chore(release): {{.SEMVER}}"'
      - echo "Push the branch '{{.BRANCH}}'. Once merged, tag the release using 'task release:tag'"

  release:tag:
    requires:
      vars: [VERSION]
    vars:
      SEMVER:
        sh: ./scripts/semver.sh {{.VERSION}}
    cmds:
      - git fetch origin -t
      - git checkout origin/main
      - git tag {{.SEMVER}}
      - echo "Push the tag '{{.SEMVER}}' to release"
