name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: mindsers/changelog-reader-action@v2
        id: changelog_reader
        with:
          version: ${{ github.ref_name }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog_reader.outputs.changes }}
      - name: Refresh docs
        run: curl https://sum.golang.org/lookup/github.com/s2-streamstore/s2-sdk-go@${{ github.ref_name }}
